use_frameworks!

platform :ios, '10.0'

target 'NRAutoIncreasingTextView_Example' do
  pod 'NRAutoIncreasingTextView', :path => '../'

  target 'NRAutoIncreasingTextView_Tests' do
    inherit! :search_paths

    
  end
end
